version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: ./internal/database
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
